spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: root
    password:
  h2:
    console:
      enabled: true
      path: /h2
  jackson:
    date-format: dd/MM/yyyy HH:mm:ss
    serialization:
      write-dates-as-timestamps: false
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8080

